services:
  remote-backtest-app:
    image: remote-backtest-app:1.0-SNAPSHOT
    build:
      context: .
    env_file:
      - docker-remote-backtest.env
    environment:
      - JAVA_OPTS=-Dhttp.proxyHost=proxy-server -Dhttp.proxyPort=8080  # Optional, wenn ein Proxy verwendet wird
    network_mode: host
    volumes:
      - /srv/docker/remote-backtest/logs:/app/logs
      - /srv/docker/krypto-java:/root/.config/krypto-java

networks:
  default:
    driver: bridge
